FROM mysql:5.5

# This file contains environment variables
# Only used for development environment
ENV MYSQL_DATABASE ${MYSQL_DATABASE:-flask_app}
ENV MYSQL_USER ${MYSQL_USER:-dev}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD:-dev}
ENV MYSQL_RANDOM_ROOT_PASSWORD ${MYSQL_RANDOM_ROOT_PASSWORD:-yes}

COPY database/ /docker-entrypoint-initdb.d/
