version: '2'

services:
  phonebook-db:
    container_name: phonebook-db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always

  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-db
    ports:
      - "8181:8181"
    restart: always
