version: '2'

services:
  phonebook-db:
    container_name: phonebook-db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
  simplephone:
    container_name: simplephone
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-db
    ports:
      - "80:5000"
    restart: always
