name: Build docker image and publish it to Docker Hub

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_HUB: ${{secrets.DOCKER_HUB}}
  DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}

version: 2

jobs:
  build--push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tenhaus/get-release-or-tag@v2
        id: tag
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_IMAGE:${{ steps.tag.outputs.tag }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.tag.outputs.tag }}